// Copyright Priordium. All Rights Reserved.
//
// Test_MapGenerator_Structure.cpp
// Structural / reflection tests for AMapGenerator.

#include "CoreMinimal.h"
#include "Misc/AutomationTest.h"
#include "AMapGenerator.h"

// -----------------------------------------------------------------------
// Test: AMapGenerator is a UClass (reflection registered)
// -----------------------------------------------------------------------

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FTest_MapGenerator_ClassRegistered,
	"Priordium.MapGenerator.AMapGenerator.Structure.ClassRegistered",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter
)
bool FTest_MapGenerator_ClassRegistered::RunTest(const FString& Parameters)
{
	UClass* Class = AMapGenerator::StaticClass();
	TestNotNull(TEXT("AMapGenerator::StaticClass() is not null"), Class);
	return true;
}

// -----------------------------------------------------------------------
// Test: AMapGenerator inherits from AActor
// -----------------------------------------------------------------------

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FTest_MapGenerator_InheritsActor,
	"Priordium.MapGenerator.AMapGenerator.Structure.InheritsActor",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter
)
bool FTest_MapGenerator_InheritsActor::RunTest(const FString& Parameters)
{
	TestTrue(TEXT("AMapGenerator derives from AActor"),
		AMapGenerator::StaticClass()->IsChildOf(AActor::StaticClass()));
	return true;
}

// -----------------------------------------------------------------------
// Test: AMapGenerator CDO is valid (proves UCLASS registration succeeded)
// -----------------------------------------------------------------------

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FTest_MapGenerator_CDOValid,
	"Priordium.MapGenerator.AMapGenerator.Structure.CDOValid",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter
)
bool FTest_MapGenerator_CDOValid::RunTest(const FString& Parameters)
{
	UClass* Class = AMapGenerator::StaticClass();
	UObject* CDO  = Class ? Class->GetDefaultObject() : nullptr;
	TestNotNull(TEXT("AMapGenerator CDO is not null"), CDO);
	return true;
}

// -----------------------------------------------------------------------
// Test: Component properties exist and are accessible
// -----------------------------------------------------------------------

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FTest_MapGenerator_ComponentPropertiesExist,
	"Priordium.MapGenerator.AMapGenerator.Structure.ComponentPropertiesExist",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter
)
bool FTest_MapGenerator_ComponentPropertiesExist::RunTest(const FString& Parameters)
{
	UClass* Class = AMapGenerator::StaticClass();

	TestNotNull(TEXT("HeightmapGenerator property exists"),
		Class->FindPropertyByName(TEXT("HeightmapGenerator")));
	TestNotNull(TEXT("BiomeManager property exists"),
		Class->FindPropertyByName(TEXT("BiomeManager")));
	TestNotNull(TEXT("LandscapeBuilder property exists"),
		Class->FindPropertyByName(TEXT("LandscapeBuilder")));
	TestNotNull(TEXT("WaterSystemBuilder property exists"),
		Class->FindPropertyByName(TEXT("WaterSystemBuilder")));
	TestNotNull(TEXT("ClimateZoneManager property exists"),
		Class->FindPropertyByName(TEXT("ClimateZoneManager")));
	TestNotNull(TEXT("ResourceDistributor property exists"),
		Class->FindPropertyByName(TEXT("ResourceDistributor")));

	return true;
}

// -----------------------------------------------------------------------
// Test: bAutoGenerateOnBeginPlay property exists and defaults to false
// -----------------------------------------------------------------------

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FTest_MapGenerator_AutoGenerateDefault,
	"Priordium.MapGenerator.AMapGenerator.Structure.AutoGenerateDefault",
	EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter
)
bool FTest_MapGenerator_AutoGenerateDefault::RunTest(const FString& Parameters)
{
	UClass* Class = AMapGenerator::StaticClass();
	FProperty* Prop = Class->FindPropertyByName(TEXT("bAutoGenerateOnBeginPlay"));
	TestNotNull(TEXT("bAutoGenerateOnBeginPlay property exists"), Prop);

	// Create a CDO-equivalent: use the class default object
	AMapGenerator* CDO = Cast<AMapGenerator>(Class->GetDefaultObject());
	if (TestNotNull(TEXT("CDO is valid"), CDO))
	{
		TestFalse(TEXT("bAutoGenerateOnBeginPlay defaults to false"), CDO->bAutoGenerateOnBeginPlay);
	}
	return true;
}
