// Copyright Priordium. All Rights Reserved.
//
// UClimateZoneManager.h
// ActorComponent that determines the climate zones of the map based on the biome map.
// SOLID: Single Responsibility -- exclusively climate zone determination and query.
//        Open/Closed -- new climate zone logic can be added without modifying the existing interface.

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "EClimateZone.h"
#include "FBiomeCell.h"
#include "FSeasonProfile.h"
#include "UClimateZoneManager.generated.h"

class UMapGeneratorSettings;

/**
 * UClimateZoneManager
 * ActorComponent that:
 */
UCLASS(ClassGroup = (MapGenerator), meta = (BlueprintSpawnableComponent))
class PRIORDIUM_API UClimateZoneManager : public UActorComponent
{
	GENERATED_BODY()

public:

	UClimateZoneManager();

	// -------------------------------------------------------------------------
	// -------------------------------------------------------------------------

	/**
	 * Determines the climate zone of a biome cell based on temperature and height.
	 * Altitude correction: if Height > 0.7, temperature decreases by -0.2f.
	 *
	 * Thresholds:
	 *   Temperature > 0.75 && Moisture > 0.5  -> Tropical
	 *   Temperature > 0.4                     -> Temperate
	 *   Temperature > 0.2                     -> Continental
	 *   otherwise                             -> Subarctic
	 *
	 * @param Cell  The biome cell to examine
	 * @return      The determined climate zone
	 */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Climate")
	EClimateZone DetermineClimateZone(const FBiomeCell& Cell) const;

	// -------------------------------------------------------------------------
	// -------------------------------------------------------------------------

	/**
	 * Calculates the climate zones of the full biome map.
	 * Populates the ClimateZoneMap array.
	 *
	 * @param BiomeMap  Cell array generated by BiomeManager
	 * @param Settings  Generation parameters
	 * @return          true if successful, false if BiomeMap is empty
	 */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Climate")
	bool CalculateClimateZones(const TArray<FBiomeCell>& BiomeMap, const UMapGeneratorSettings* Settings);

	/**
	 * Queries the climate zone by index.
	 * Returns Temperate for an invalid index.
	 *
	 * @param Index  Linear index of the cell
	 * @return       The climate zone, or Temperate if the index is invalid
	 */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Climate")
	EClimateZone GetClimateZoneAt(int32 Index) const;

	/** Returns whether the ClimateZoneMap is populated. */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Climate")
	bool IsInitialized() const { return ClimateZoneMap.Num() > 0; }

	// -------------------------------------------------------------------------
	// -------------------------------------------------------------------------

	/**
	 * Calculates the seasonally adjusted temperature for a base temperature value.
	 * Uses cosine interpolation between WinterTempModifier and SummerTempModifier.
	 *
	 * TimeOfYear = 0.0 -> Winter -> BaseTemp + WinterTempModifier
	 * TimeOfYear = 0.5 -> Summer -> BaseTemp + SummerTempModifier
	 *
	 * Result is clamped to [0, 1].
	 *
	 * @param BaseTemp    The base cell temperature [0, 1]
	 * @param TimeOfYear  Season position [0, 1] where 0=winter, 0.5=summer
	 * @return            Adjusted temperature [0, 1]
	 */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Climate")
	float CalculateSeasonalTemperature(float BaseTemp, float TimeOfYear) const;

	/**
	 * Returns the seasonally adjusted temperature of a cell by index.
	 * Requires CalculateClimateZones() to have been called first.
	 * Returns -1.0 for invalid index.
	 *
	 * @param Index       Linear cell index
	 * @param TimeOfYear  Season position [0, 1] where 0=winter, 0.5=summer
	 * @return            Adjusted temperature [0, 1], or -1.0 on error
	 */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Climate")
	float GetTemperatureAt(int32 Index, float TimeOfYear = 0.5f) const;

	/** Season modifier profile used for temperature calculations. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Map Generator|Climate",
		meta = (ToolTip = "Seasonal temperature modifiers. SummerTempModifier applied at TimeOfYear=0.5, WinterTempModifier at 0.0."))
	FSeasonProfile SeasonProfile;

	// -------------------------------------------------------------------------
	// -------------------------------------------------------------------------

	/**
	 * The calculated climate zone map (runtime cache).
	 * Kept out of Details to avoid editor stalls when large maps are generated.
	 * Index = Y * Resolution.X + X
	 */
	TArray<EClimateZone> ClimateZoneMap;

protected:

	virtual void BeginPlay() override;

private:

	/** Map resolution (X = columns, Y = rows). */
	FIntPoint Resolution = FIntPoint(0, 0);

	/** Base temperature per cell, populated by CalculateClimateZones(). */
	TArray<float> TemperatureMap;
};
