// Copyright Priordium. All Rights Reserved.
//
// ULandscapeBuilder.h
// ActorComponent that uses the UE Landscape system to create the actual terrain actor.
// SOLID: Single Responsibility -- exclusively creates and configures the Landscape actor.
//        Open/Closed -- new build steps can be added without modifying the existing interface.

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "EBiomeType.h"
#include "LandscapeProxy.h"
#include "LandscapeLayerInfoObject.h"
#include "ULandscapeBuilder.generated.h"

class UMapGeneratorSettings;
class UHeightmapGenerator;
class UBiomeManager;
class ALandscape;
class UMaterialInterface;

/**
 * ULandscapeBuilder
 * ActorComponent that:
 */
UCLASS(ClassGroup = (MapGenerator), meta = (BlueprintSpawnableComponent))
class PRIORDIUM_API ULandscapeBuilder : public UActorComponent
{
	GENERATED_BODY()

public:

	ULandscapeBuilder();

	// -------------------------------------------------------------------------
	// -------------------------------------------------------------------------

	/** Returns the most recently generated Landscape actor, or null if not yet created. */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Landscape")
	ALandscapeProxy* GetGeneratedLandscape() const { return GeneratedLandscape; }

	/** Returns whether the Landscape was successfully created. */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Landscape")
	bool IsLandscapeCreated() const { return GeneratedLandscape != nullptr; }

	// -------------------------------------------------------------------------
	// -------------------------------------------------------------------------

	/**
	 * Converts float [0, 1] heightmap data to uint16 [0, 65535] format
	 * for the UE Landscape import API.
	 * Note: TArray<uint16> is not Blueprint-compatible, so not BlueprintCallable.
	 *
	 * @param Heightmap   The normalized [0, 1] float heightmap data
	 * @return            uint16 array for Landscape import
	 */
	TArray<uint16> ConvertHeightmapToUint16(const TArray<float>& Heightmap) const;

	// -------------------------------------------------------------------------
	// -------------------------------------------------------------------------

	/**
	 * Layer Info Object assets per biome type.
	 * Key: EBiomeType, Value: ULandscapeLayerInfoObject asset reference.
	 * Must be manually assigned in the editor,
	 * or can be automatically loaded with the LoadLayerInfoAssets() method.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Map Generator|Landscape|Layers",
		meta = (ToolTip = "Layer Info Objects per biome type. Assign in editor or call LoadLayerInfoAssets()."))
	TMap<EBiomeType, TObjectPtr<ULandscapeLayerInfoObject>> LayerInfoAssets;

	/**
	 * Automatically loads Layer Info Object assets from the Content Browser.
	 * Searches for assets in the /Game/Landscape/Layers/ folder
	 * with names LI_Ocean, LI_Beach, LI_Plains, LI_Forest, LI_Hills, LI_Mountain, LI_Swamp.
	 *
	 * @return true if at least one layer info was found for every biome
	 */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Landscape|Layers")
	bool LoadLayerInfoAssets();

	/** Returns whether a Layer Info is assigned for every biome. */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Landscape|Layers")
	bool AreAllLayersLoaded() const;

	// -------------------------------------------------------------------------
	// -------------------------------------------------------------------------

	/**
	 * Entry point of the full Landscape build pipeline.
	 * 1. Heightmap conversion generated by HeightmapGenerator
	 * 2. Landscape actor creation
	 * 3. Heightmap import
	 * 4. Transform configuration
	 *
	 * @param Settings   Generation parameters
	 * @param Heightmap  The already-generated heightmap component
	 * @param Biome      (optional) BiomeManager for painting material layers
	 * @return           true if successful
	 */
	UFUNCTION(BlueprintCallable, Category = "Map Generator|Landscape")
	bool BuildLandscape(const UMapGeneratorSettings* Settings, UHeightmapGenerator* Heightmap, UBiomeManager* Biome = nullptr);

	// -------------------------------------------------------------------------
	// -------------------------------------------------------------------------

	/**
	 * Calculates weight maps from the BiomeManager blend weight data.
	 * Generates a TArray<uint8> array for each biome,
	 * whose values are in the [0, 255] range (float [0,1] * 255).
	 * Note: TMap<EBiomeType, TArray<uint8>> is not Blueprint-compatible.
	 *
	 * @param Biome       Component containing the biome data
	 * @param Resolution  Map resolution (NxN vertices)
	 * @return            uint8 weight maps per biome
	 */
	TMap<EBiomeType, TArray<uint8>> CalculateWeightMaps(UBiomeManager* Biome, int32 Resolution) const;

	/**
	 * Applies material layer weight maps to the Landscape.
	 * Only available in editor builds (LandscapeEditorUtils::SetWeightmapData).
	 * Does nothing if no LayerInfoAssets are assigned.
	 *
	 * @param Landscape   The target Landscape actor
	 * @param Biome       Component containing the biome data
	 * @param Resolution  Map resolution
	 * @return            true if at least one layer was successfully applied
	 */
	bool ApplyMaterialLayers(ALandscape* Landscape, UBiomeManager* Biome, int32 Resolution);

protected:

	virtual void BeginPlay() override;

private:

	/** Weak pointer to the most recently generated Landscape actor. */
	UPROPERTY()
	TObjectPtr<ALandscapeProxy> GeneratedLandscape = nullptr;

	// -------------------------------------------------------------------------
	// -------------------------------------------------------------------------

	/**
	 * Spawns a Landscape actor into the world.
	 * @param World      The current world
	 * @param Transform  The initial transform of the Landscape
	 * @return           The new ALandscape pointer, or null on error
	 */
	ALandscape* CreateLandscape(UWorld* World, const FTransform& Transform);

	/**
	 * Imports heightmap data into the Landscape.
	 * @param Landscape      The target Landscape actor
	 * @param HeightData     uint16 heightmap data
	 * @param Resolution     Heightmap resolution (NxN)
	 * @return               true if successful
	 */
	bool ImportHeightmap(ALandscape* Landscape, const TArray<uint16>& HeightData, int32 Resolution);

	/**
	 * Configures Landscape transform: center positioning and QuadSize scale.
	 * @param Landscape  The configured Landscape
	 * @param Settings   Generation parameters (Resolution, QuadSize)
	 */
	void ConfigureLandscapeTransform(ALandscape* Landscape, const UMapGeneratorSettings* Settings);

	/**
	 * Returns the grass landscape material, creating it as a new asset if it doesn't exist yet.
	 * Asset path: /Game/Landscape/M_Landscape_Grass
	 */
	UMaterialInterface* GetOrCreateGrassMaterial();
};


